### ISSUE TITLE
Vundle 有新版本了

### ISSUE THREAD

**Issue by yumao5** [sg552/happy_book_vim#1]
安装的时候会报错，E117: Unknown function: vundle#rc

按新版本的语法改就可以了。

call vundle#begin()
...
call vundle#end()            " required

**Comment by sg552** [comment]
恩,不要用最新的 Vundle, 我这个跟最新的Vundle 不兼容. 

现在你只需要把整个 repo clone 下来,  把 .vim 和 .vimrc 放到home目录下,就可以用了.
