### ISSUE TITLE
两个bundle安装失败

### ISSUE THREAD

**Issue by samniu** [sg552/happy_book_vim#2]
下面这两个bundle安装失败，翻墙也不行。

```
Bundle 'git://git.wincent.com/command-t.git'
Bundle 'tsaleh/vim-matchit.git'
```

**Comment by sg552** [comment]
恩,我更新了 repo, 把我本地的plugin 放上去了. 

现在你只需要把整个 repo clone 下来,  把 .vim 和 .vimrc 放到home目录下,就可以用了.

有问题随时联系我~
